### ISSUE TITLE
Appendix support

### ISSUE THREAD

**Issue by tgherzog** [grimbough/msmbstyle#27]
I'm trying to use your terrific package to generate a book with an Appendix, using [this bookdown feature](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#special-headers) to number the Appendices separately (A, B, etc). My testing stub is below.

The trouble is that the appendices are numbered incorrectly in the TOC dropdown, although their section titles are correct on the page.

![image](https://user-images.githubusercontent.com/1315823/96464286-a18d8c00-11f5-11eb-900b-7176c9ea96f4.png)

I'm using the latest version of msmbstyle `0.0.15` installed from github this morning.

````
---
site: bookdown::bookdown_site
title: "Foobar: A Novel"
author: "Tim Herzog"
date: "`r Sys.Date()`"
output:
  bookdown::pdf_book:
    includes:
      in_header: preamble.tex
    latex_engine: xelatex
    # citation_package: natbib
    keep_tex: no
    toc: no
    title: no
  bookdown::html_book:
    toc: true
    number_sections: true
  msmbstyle::msmb_html_book:
    toc: true
    number_sections: true
documentclass: book
classoption:
 - openright
 - oneside
# bibliography: [book.bib, packages.bib]
# biblio-style: apalike
# link-citations: yes
---

# Introduction

Yada yada yada

# Chapter Two #

Dark and stormy night

# (APPENDIX) Appendix {-}

# List of Preferred Holloween Candies

* Recess peanut butter cups
* Snickers
* M&Ms

# Shopping List

* Toilet paper
* Paint brushes

````
