### ISSUE TITLE
font size and a few other small things in grid-layout

### ISSUE THREAD

**Issue by ericpgreen** [grimbough/msmbstyle#5]
Loving how the html is rendered in the `grid-layout` branch. A few questions:

1. What would be the correct custom css style to change the font size and style for the body copy? That would be the text within sections and rows, I think. I tried changing `body` but that changed the section TOC.

2. Is it possible to put figure numbers with the captions in margin notes?

3. How did you "turn off" footnote numbers in the margin notes?

**Comment by grimbough** [comment]
Thanks for the feedback.  

1. Is it sufficient to modify the `<p>` tag?  Including the following in a custom CSS file makes the main text larger for me, without modifying either the navigation panel or the things in the right margin.  It also ignores and code blocks etc.

```css
p {
    font-size: 2em;
    line-height: 1;
}
```
It's entirely likely that my CSS is not complete enough at the moment to achieve what you want, so happy to add new classes or tags if it makes custom themes easier.

2.  Figure numbers are supposed to be there by default, and I hadn't realised they weren't!  I'll investigate.

3. I think I should clarify that there are several ways things can end up in the margin.  

The following Markdown syntax should produce a numbered footnote beside the relevant paragraph.  The footnote text itself can appear anywhere in the Markdown document.

```
Text in the body of the chapter. [^1]

[^1]: A numbered footnote beside it.
```

If you want a comment in the margin, but without numbering you can use the something like this inline code:

```
`r msmbstyle::margin_note('The code is shown here; hide it via \x60echo = FALSE\x60')`
```
The `\x60` parts will get translated into backticks when the document is processed so anything inside them is rendered in `typewriter font` and the text is currently prefaced with the 🛈 symbol since this is extra information.

There's also the `marginfigure` code block for more complex content e.g.

````
```{marginfigure, echo = TRUE}
We know from _the first fundamental theorem of calculus_ that for $x$ in $[a, b]$:
$$\frac{d}{dx}\left( \int_{a}^{x} f(u)\,du\right)=f(x).$$
```
````

**Comment by ericpgreen** [comment]
Wonderful. Thanks for the very helpful tips.

Showing here that I don't seem to get a Figure number by default. I'm also getting some whitespace in the main text due to the margin figure. Is there a better way to include an image like this in the margin?

![screenshot 2019-01-04 11 15 15](https://user-images.githubusercontent.com/546433/50698140-281dad00-1012-11e9-9fe3-2d7a0ce57caf.png)

```
--- 
title: "Global Health Research: Designs and Methods"
author: "Eric P. Green"
date: "`r Sys.Date()`"
cover-image: "images/cover.jpg"
knit: "bookdown::preview_chapter"
site: "bookdown::bookdown_site"
monofont: "Inconsolata"
monofontoptions: "Scale=0.7"
bibliography: [book.bib, packages.bib, ghr.bib]
biblio-style: apalike
link-citations: yes
description: "Online textbook about global health research methods"
output:
  msmbstyle::msmb_html_book:
    toc: TRUE
    toc_depth: 1
    split_by: chapter
    split_bib: no
    margin_references: FALSE
    css: style.css
---

# Preface{-}

This book will introduce you to research designs and methods in global health. I wrote this text for undergraduate and graduate students taking my [introductory course at Duke University](http://www.globalhealthresearch.co/). Therefore, it shares the two central aims of my course: to make you a better consumer of research and to help you design your first study.

```{r cover, echo=F, fig.margin=TRUE, fig.cap="A caption."}
  knitr::include_graphics("images/cover.jpg", dpi = NA)
```
```
